Repository ironcore-dev/libvirt-provider, pull requests merged in 2024-08, with the labels that each got.

#369 Fix Dockerfile Annotation Warnings
  Dockerfile
Labels: size/S

#370 Extend Server Tests to Cover ListEvents
  internal/server/event_list_test.go
  internal/server/server_suite_test.go
Labels: size/L, integration-tests

#388 Fix potential nil-pointer deref in last volume size event
  .github/workflows/golangci-lint.yml
  Makefile
  go.mod
  go.sum
  internal/controllers/machine_controller.go
  internal/controllers/machine_controller_volumes.go
  internal/event/machineevent/machineevent_test.go
Labels: bug, size/M
