Repository ironcore-dev/libvirt-provider, pull requests merged in 2024-06, with the labels that each got.

#324 Fixed health check configuration
  cmd/libvirt-provider/app/app.go
  config/manager/manager.yaml
  internal/server/server_suite_test.go
Labels: size/XS, integration-tests

#325 Fix health check server
  cmd/libvirt-provider/app/app.go
  config/manager/manager.yaml
Labels: size/XS

#327 Fixed `NIC` PCI address conflict
  internal/controllers/machine_controller_nics.go
Labels: bug, size/XS, integration-tests
