Repository ironcore-dev/libvirt-provider, pull requests merged in 2024-04, with the labels that each got.

#264 Overcommit VCPU for Scheduling
  pkg/resources/manager/functions.go
  pkg/resources/manager/manager_test.go
  pkg/resources/sources/cpu.go
  pkg/resources/sources/dummy.go
  pkg/resources/sources/memory.go
  pkg/resources/sources/options.go
  provider/cmd/app/app.go
Labels: size/M, dt-target

#272 Restructuring Resource Manager
  pkg/resources/manager/interfaces.go
  pkg/resources/manager/manager.go
  pkg/resources/manager/manager_test.go
  pkg/resources/sources/cpu.go
  pkg/resources/sources/dummy.go
  pkg/resources/sources/memory.go
  provider/server/machine.go
  provider/server/machine_create.go
  provider/server/machine_list.go
Labels: size/L, server, dt-target

#277 Reserving Hugepages and Memory
  pkg/resources/manager/functions.go
  pkg/resources/sources/cpu.go
  pkg/resources/sources/hugepages.go
  pkg/resources/sources/memory.go
  pkg/resources/sources/options.go
  provider/cmd/app/app.go
Labels: size/L, dt-target

#279 limiting Count of VMs
  pkg/resources/manager/functions.go
  pkg/resources/manager/manager.go
  pkg/resources/sources/options.go
  provider/cmd/app/app.go
Labels: enhancement, size/M, dt-target

#293 implement sgx
  config/development/machineclasses.json
  pkg/controllers/machine_controller.go
  pkg/mcr/registry.go
  pkg/resources/manager/functions.go
  pkg/resources/manager/interfaces.go
  pkg/resources/manager/machineclasses.go
  pkg/resources/manager/manager.go
  pkg/resources/manager/manager_test.go
  pkg/resources/sources/cpu.go
  pkg/resources/sources/dummy.go
  pkg/resources/sources/global.go
  pkg/resources/sources/hugepages.go
  pkg/resources/sources/memory.go
  pkg/sgx/sgx.go
  pkg/sgx/source.go
  provider/cmd/app/app.go
Labels: size/XL, controllers
