Repository ironcore-dev/libvirt-provider, pull requests merged in 2025-03, with the labels that each got.

#505 Added support for TAP devices
  .github/workflows/publish-docker.yml
  go.mod
  go.sum
  internal/controllers/machine_controller.go
  internal/controllers/machine_controller_nics.go
  internal/plugins/networkinterface/apinet/apinet.go
  internal/plugins/networkinterface/plugins.go
Labels: size/L

#517 Adapt to latest `OCI` format
  internal/controllers/machine_controller.go
  internal/oci/image.go
Labels: bug, size/S

#520 Bump dependencies
  .github/workflows/golangci-lint.yml
  Dockerfile
  Makefile
  REUSE.toml
  go.mod
  go.sum
  internal/server/machine_create_test.go
  internal/server/machine_delete_test.go
  internal/server/server_suite_test.go
Labels: enhancement, size/L, integration-tests

#532 Use upstream docs publishing workflow
  .github/workflows/publish-docs.yml
Labels: size/M

#534 Fix `cpu` selection
  internal/controllers/machine_controller.go
Labels: bug, size/XS
